"""The markdown backend: one file per open record, in a store workers share by path.

WHAT THIS BUYS OVER TASKS, AND IT IS ONE THING. Tasks' git-tracked artefact is
`issues.jsonl` — a blob that diffs badly and reviews worse. This backend's tracked
artefact is per-record markdown, so the once-per-wave sync produces a reviewable diff.
Everything else here is the cost of getting that.

TWO STORES, MIRRORING TASKS, and the split is forced by three rules the harness already
enforces rather than by taste:

    .tasks/          GITIGNORED, worker-writable, reached by ABSOLUTE PATH into the
                     primary checkout — exactly as `BEADS_DB` is. Workers write here
                     during a wave, so the checkout stays clean and their writes are not
                     swept into a sibling's commit.
    <export>/        TRACKED, regenerated by the orchestrator once per wave at the point
                     `swarm.md` already runs `bd export -o`. One actor, one writer.

LOCATION WAS NEVER THE CONSTRAINT. A store under `docs/proposed/<epic>/` would be shared
just as well, since sharing comes from the absolute path and not from where in the tree it
sits. What binds is TRACKEDNESS: a tracked file written by eight workers mid-wave leaves
the primary checkout permanently dirty and fails the next wave's pre-flight.

RETENTION IS A PERFORMANCE QUESTION HERE, WHICH IT IS NOT IN A DATABASE. `ready` parses
the directory on every call, so keeping every closed record forever makes the scheduler
slower each wave. Closed records compact into `archive.jsonl`; `show` falls back to it, so
a reference to a closed record still RESOLVES — the distinction between a dependency
*satisfied* and one *missing*, which the scheduler cannot guess. Decisions stay hot
whatever their status, because they are read as live constraints long after they close.
"""

from __future__ import annotations

import json
import os
import re
import secrets
import tempfile
from datetime import datetime, timezone
from pathlib import Path

from . import graph
from .locks import run_dir
from .port import (
    CLOSED,
    DECISION,
    GATE,
    OPEN,
    OPEN_STATUSES,
    TASK,
    Capabilities,
    NotSupported,
    Task,
    TrackerError,
    Validation,
)

#: Set by `.swarm-env` for a worker, the same way `BEADS_DB` is, so every worktree writes
#: the primary checkout's store rather than its own branch's copy.
TASKS_DIR_ENV = "TASKS_DIR"

_FRONTMATTER = re.compile(r"\A---\n(.*?)\n---\n?(.*)\Z", re.DOTALL)
_NOTES_HEADING = "## Notes"
_ACCEPTANCE_HEADING = "## Acceptance criteria"


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _dump_scalar(v) -> str:
    if isinstance(v, (list, tuple)):
        return "[" + ", ".join(str(x) for x in v) + "]"
    return "" if v is None else str(v)


def _load_scalar(raw: str):
    raw = raw.strip()
    if raw.startswith("[") and raw.endswith("]"):
        inner = raw[1:-1].strip()
        return tuple(x.strip() for x in inner.split(",") if x.strip())
    if raw.isdigit():
        return int(raw)
    return raw


class MdTaskStore:
    """`TaskStore` over a directory of markdown files.

    :param root: the hot store. Defaults to `$TASKS_DIR`, else `<primary>/.tasks`.
    :param export_dir: where `export()` writes the tracked copy.
    """

    def __init__(self, root: Path | None = None, export_dir: Path | None = None) -> None:
        env = os.environ.get(TASKS_DIR_ENV)
        self.root = Path(root) if root else Path(env) if env else run_dir().parent / "tasks"
        self.export_dir = Path(export_dir) if export_dir else None

    # --- capabilities ---------------------------------------------------------

    def capabilities(self) -> Capabilities:
        return Capabilities(
            name="mdfiles",
            #: NO CEILING. A file per record has no size limit, so every guard that exists
            #: because tasks fails closed past ~64KB is inert here — and says so rather
            #: than warning about nothing forever.
            record_bytes=None,
            molecules=False,
            prime=False,
            tracked_export=True,
            owned_paths=self._owned_paths(),
            export_path=self._rel(self.export_dir) if self.export_dir else None,
        )

    @staticmethod
    def _rel(path: Path) -> str:
        """A directory as the repository sees it, trailing slash and all. A path outside
        the repository — the hot store is addressed absolutely, by design, so every
        worktree shares one — is reported as-is."""
        from models.resolve import RepoError, repo_root

        resolved = Path(path).resolve()
        try:
            return f"{resolved.relative_to(repo_root())}/"
        except (ValueError, RepoError):
            return f"{resolved}/"

    def _owned_paths(self) -> tuple[str, ...]:
        """The hot store and the tracked export, repo-relative where they are in the repo.

        Both are configured rather than fixed, so they can only be declared by asking the
        instance.
        """
        from models.resolve import repo_root

        try:
            repo_root()
        except Exception:
            return ()
        return tuple(sorted({self._rel(p) for p in (self.root, self.export_dir) if p is not None}))

    # --- storage --------------------------------------------------------------

    @property
    def _archive(self) -> Path:
        return self.root / "archive.jsonl"

    def _path(self, task_id: str) -> Path:
        return self.root / f"{task_id}.md"

    def _new_id(self) -> str:
        """A short, collision-resistant id.

        RANDOM, NOT A COUNTER. Eight workers create records concurrently in one shared
        directory; a counter would need a lock around every create, and a lost update
        there hands two records the same id — which the archive then cannot tell apart.
        """
        return f"t-{secrets.token_hex(3)}"

    def _write(self, task: Task) -> None:
        """Whole-file write via os.replace, so a concurrent reader never sees a partial."""
        self.root.mkdir(parents=True, exist_ok=True)
        fields = {
            "id": task.id,
            "type": task.type,
            "status": task.status,
            "title": task.title,
            "priority": task.priority,
            "parent": task.parent,
            "depends_on": task.depends_on,
            "labels": task.labels,
            "assignee": task.assignee,
            "created_at": task.created_at,
            "updated_at": task.updated_at,
            # UNMODELLED-BUT-DURABLE fields. `close_reason` is why `close()` requires one
            # at all — a close that records nothing is the thing the required argument
            # exists to prevent — and `superseded_by` is what makes a supersede chain
            # followable. Both lived only in `raw`, which is rebuilt from frontmatter on
            # read, so both were silently discarded the moment the record was written.
            "close_reason": task.raw.get("close_reason"),
            "superseded_by": task.raw.get("superseded_by"),
        }
        head = "\n".join(
            f"{k}: {_dump_scalar(v)}" for k, v in fields.items() if v not in (None, "", ())
        )
        body = task.description.rstrip()
        if task.acceptance.strip():
            body += f"\n\n{_ACCEPTANCE_HEADING}\n\n{task.acceptance.strip()}"
        if task.notes.strip():
            body += f"\n\n{_NOTES_HEADING}\n\n{task.notes.strip()}"
        text = f"---\n{head}\n---\n\n{body.strip()}\n"

        fd, tmp = tempfile.mkstemp(dir=str(self.root), prefix=".w-")
        with os.fdopen(fd, "w") as fh:
            fh.write(text)
        os.replace(tmp, self._path(task.id))

    def _read(self, path: Path) -> Task | None:
        try:
            text = path.read_text()
        except OSError:
            return None
        m = _FRONTMATTER.match(text)
        if not m:
            return None
        fields: dict = {}
        for line in m.group(1).splitlines():
            if ":" not in line:
                continue
            key, _, raw = line.partition(":")
            fields[key.strip()] = _load_scalar(raw)
        body = m.group(2)
        notes = acceptance = ""
        if _NOTES_HEADING in body:  # last section first, so its text cannot shadow the others
            body, _, notes = body.partition(_NOTES_HEADING)
        if _ACCEPTANCE_HEADING in body:
            body, _, acceptance = body.partition(_ACCEPTANCE_HEADING)
        return Task(
            id=str(fields.get("id") or path.stem),
            type=str(fields.get("type") or TASK),
            status=str(fields.get("status") or OPEN),
            title=str(fields.get("title") or ""),
            description=body.strip(),
            acceptance=acceptance.strip(),
            notes=notes.strip(),
            priority=fields.get("priority") if isinstance(fields.get("priority"), int) else None,
            parent=str(fields["parent"]) if fields.get("parent") else None,
            depends_on=tuple(fields.get("depends_on") or ()),
            labels=tuple(fields.get("labels") or ()),
            assignee=str(fields["assignee"]) if fields.get("assignee") else None,
            created_at=str(fields.get("created_at") or ""),
            updated_at=str(fields.get("updated_at") or ""),
            close_reason=str(fields.get("close_reason") or ""),
            raw=fields,
        )

    def _archived(self) -> dict[str, Task]:
        out: dict[str, Task] = {}
        if not self._archive.is_file():
            return out
        for line in self._archive.read_text().splitlines():
            if not line.strip():
                continue
            try:
                d = json.loads(line)
            except json.JSONDecodeError:
                continue  # a torn final line must not lose the rest of the history
            out[d["id"]] = Task(
                id=d["id"],
                type=d.get("type", TASK),
                status=d.get("status", CLOSED),
                title=d.get("title", ""),
                description=d.get("close_reason", ""),
                depends_on=tuple(d.get("depends_on") or ()),
                parent=d.get("parent"),
                updated_at=d.get("closed_at", ""),
                close_reason=str(d.get("close_reason") or ""),
                raw=d,
            )
        return out

    def _hot(self) -> list[Task]:
        if not self.root.is_dir():
            return []
        out = []
        for p in sorted(self.root.glob("*.md")):
            t = self._read(p)
            if t is not None:
                out.append(t)
        return out

    def _compact(self, task: Task) -> None:
        """Move a closed record into the archive. Decisions never leave the hot store.

        A closed decision is settled, NOT irrelevant: the survey reads them as binding
        constraints and the register check verifies their status. Compacting one would
        answer those questions from a summary that has dropped its resolution.
        """
        if task.type == DECISION:
            return
        self.root.mkdir(parents=True, exist_ok=True)
        row = {
            "id": task.id,
            "type": task.type,
            "status": task.status,
            "title": task.title,
            "closed_at": task.updated_at,
            "close_reason": task.raw.get("close_reason", ""),
            "superseded_by": task.raw.get("superseded_by"),
            "depends_on": list(task.depends_on),
            "parent": task.parent,
        }
        with self._archive.open("a") as fh:
            fh.write(json.dumps(row, sort_keys=True) + "\n")
        self._path(task.id).unlink(missing_ok=True)

    # --- reads ----------------------------------------------------------------

    def show(self, task_id: str) -> Task | None:
        t = self._read(self._path(task_id))
        if t is not None:
            return t
        # THE ARCHIVE FALLBACK. Without it a closed dependency reads as MISSING, and the
        # scheduler cannot tell "satisfied" from "never existed".
        return self._archived().get(task_id)

    def _all(self) -> list[Task]:
        """Hot plus archived — everything `show` could resolve."""
        return self._hot() + list(self._archived().values())

    def list(
        self,
        *,
        type: str | None = None,
        status: str | None = None,
        parent: str | None = None,
        limit: int | None = None,
    ) -> list[Task]:
        rows = self._all() if (status == CLOSED or status is None) else self._hot()
        if type:
            rows = [t for t in rows if t.type == type]
        if status:
            rows = [t for t in rows if t.status == status]
        if parent:
            rows = [t for t in rows if t.parent == parent]
        rows.sort(key=lambda t: t.id)
        return rows[:limit] if limit else rows

    def _gated_ids(self) -> set[str]:
        """Ids held by an open gate. A gate records its target in `depends_on`."""
        return {
            target
            for g in self._hot()
            if g.type == GATE and g.status in OPEN_STATUSES
            for target in g.depends_on
        }

    def ready(self, *, parent: str | None = None, limit: int | None = None) -> list[Task]:
        rows = [t for t in self._all() if t.type != GATE]
        out = graph.ready(rows, gated=self._gated_ids())
        if parent:
            out = [t for t in out if t.parent == parent]
        return out[:limit] if limit else out

    def validate(self, epic_id: str) -> Validation:
        return graph.validate([t for t in self._all() if t.parent == epic_id])

    # --- writes ---------------------------------------------------------------

    def create(
        self,
        title: str,
        *,
        type: str = TASK,
        description: str = "",
        priority: int | None = None,
        parent: str | None = None,
        labels: tuple[str, ...] = (),
    ) -> str:
        tid = self._new_id()
        now = _now()
        self._write(
            Task(
                id=tid,
                type=type,
                status=OPEN,
                title=title,
                description=description,
                priority=priority,
                parent=parent,
                labels=tuple(labels),
                created_at=now,
                updated_at=now,
            )
        )
        return tid

    def _require(self, task_id: str) -> Task:
        t = self._read(self._path(task_id))
        if t is None:
            raise TrackerError(f"no such record: {task_id}")
        return t

    def update(self, task_id: str, **fields) -> None:
        t = self._require(task_id)
        raw = dict(t.raw)
        allowed = {
            "status", "title", "description", "acceptance", "priority", "parent",
            "assignee", "labels",
        }
        changes = {k: v for k, v in fields.items() if k in allowed}
        for k, v in fields.items():
            if k not in allowed:
                raw[k] = v  # keep unmodelled fields (close_reason, superseded_by)
        merged = {**t.__dict__, **changes, "updated_at": _now(), "raw": raw}
        self._write(Task(**merged))

    def close(self, task_id: str, reason: str) -> None:
        t = self._require(task_id)
        raw = {**t.raw, "close_reason": reason}
        closed = Task(**{**t.__dict__, "status": CLOSED, "updated_at": _now(), "raw": raw})
        self._write(closed)
        self._compact(closed)

    def note(self, task_id: str, text: str) -> None:
        t = self._require(task_id)
        joined = f"{t.notes}\n\n{text}".strip() if t.notes else text
        self._write(Task(**{**t.__dict__, "notes": joined, "updated_at": _now()}))

    def dep_add(self, dependent: str, blocker: str) -> None:
        t = self._require(dependent)
        if blocker in t.depends_on:
            return
        self._write(
            Task(**{**t.__dict__, "depends_on": t.depends_on + (blocker,), "updated_at": _now()})
        )

    def supersede(self, old_id: str, new_id: str) -> None:
        t = self._require(old_id)
        raw = {**t.raw, "superseded_by": new_id, "close_reason": f"superseded by {new_id}"}
        closed = Task(**{**t.__dict__, "status": CLOSED, "updated_at": _now(), "raw": raw})
        self._write(closed)
        self._compact(closed)

    def delete(self, task_id: str) -> None:
        self._path(task_id).unlink(missing_ok=True)

    # --- gates ----------------------------------------------------------------

    def gate_create(self, blocks: str, reason: str) -> str:
        gid = self._new_id()
        now = _now()
        self._write(
            Task(
                id=gid,
                type=GATE,
                status=OPEN,
                title=f"Gate: {reason[:60]}",
                description=reason,
                depends_on=(blocks,),
                created_at=now,
                updated_at=now,
            )
        )
        return gid

    def gate_list(self) -> list[Task]:
        return [t for t in self._hot() if t.type == GATE and t.status in OPEN_STATUSES]

    def gate_resolve(self, gate_id: str) -> None:
        self.close(gate_id, "resolved")

    # --- the tracked artefact -------------------------------------------------

    def export(self, path: str | None = None) -> None:
        """Regenerate the tracked copy: per-record markdown plus the archive.

        ONE ACTOR, ONCE PER WAVE — the orchestrator, at the point it already syncs the
        tracker. A worker calling this mid-wave puts tracked files in the primary
        checkout and fails the next pre-flight, which is the whole reason the hot store
        is gitignored.
        """
        dest = Path(path) if path else self.export_dir
        if dest is None:
            raise TrackerError(
                "no export directory: pass one, or set tracker.export in harness.yaml"
            )
        dest.mkdir(parents=True, exist_ok=True)
        for stale in dest.glob("*.md"):
            stale.unlink()
        for t in self._hot():
            (dest / f"{t.id}.md").write_text(self._path(t.id).read_text())
        if self._archive.is_file():
            (dest / "archive.jsonl").write_text(self._archive.read_text())

    def autosync(self, enabled: bool) -> None:
        """A no-op that SUCCEEDS, because this backend never writes the export unasked.

        The `export.auto` dance exists because tasks stages its tracked file into whatever
        commit comes next. Here `export()` is the only writer, so there is nothing to
        disable — and refusing would make a caller think the wave is unsafe when it is
        the safe case.
        """
        return None

    def prime(self) -> str:
        raise NotSupported(
            "the markdown backend has no curated context dump. Read the tracked export, "
            "or use `list`/`ready`."
        )

    def label(self, task_id: str, name: str, *, remove: bool = False) -> None:
        t = self._require(task_id)
        labels = tuple(x for x in t.labels if x != name) + (() if remove else (name,))
        self._write(Task(**{**t.__dict__, "labels": labels, "updated_at": _now()}))


class MdMemoryStore:
    """Durable insight as `<root>/memories/<slug>.md`, the shape of a memory directory."""

    def __init__(self, root: Path | None = None) -> None:
        base = MdTaskStore(root).root if root is None else Path(root)
        self.root = base / "memories"

    def remember(self, text: str, *, key: str | None = None) -> None:
        self.root.mkdir(parents=True, exist_ok=True)
        slug = key or re.sub(r"[^a-z0-9]+", "-", text.lower())[:48].strip("-")
        (self.root / f"{slug or secrets.token_hex(3)}.md").write_text(
            f"---\nkey: {slug}\nat: {_now()}\n---\n\n{text.strip()}\n"
        )

    def memories(self) -> list[str]:
        if not self.root.is_dir():
            return []
        return [p.stem for p in sorted(self.root.glob("*.md"))]

    def recall(self, query: str) -> list[str]:
        if not self.root.is_dir():
            return []
        q = query.lower()
        return [
            p.read_text().split("---", 2)[-1].strip()
            for p in sorted(self.root.glob("*.md"))
            if q in p.read_text().lower()
        ]
