"""A readable view of one epic's plan and its current state.

WHY A VIEW AND NOT A STORE, which is what makes this cheap and safe. Every objection to
putting task state in the staging folder was about WORKER WRITES to a TRACKED file
mid-wave. This has neither property: the orchestrator writes it, at the wave boundary,
at the same point it already regenerates the tracked export. No new writer, no new
timing, no clean-tree risk.

WHY IT IS GENERATED AND DRIFT IS A FAILURE. A file in the corpus that looks authored
becomes a second source of truth the moment somebody edits it — the failure this
repository calls its most expensive defect class. Two precedents already handle this
shape rather than a third being invented: `worker.py` stamps `.swarm-env` "Do not
hand-edit", and `model:`/`effort:` are generated from tiers.yaml with
`check-model-config.sh` failing on drift. `--check` is that, for this.

BACKEND-AGNOSTIC BY CONSTRUCTION. It reads through the port, so it works against whatever
tracker a project declares and needed no markdown backend to exist.
"""

from __future__ import annotations

from pathlib import Path

from .port import CLOSED, GATE, OPEN_STATUSES, TaskStore

BANNER = (
    "<!-- GENERATED by `tk.sh render` from the tracker. Do not hand-edit — edits are\n"
    "     overwritten, and `tk.sh render --check` fails the wave gate on drift. -->"
)


def _gloss(title: str, words: int = 7) -> str:
    return " ".join(title.split()[:words])


def render_epic(store: TaskStore, epic_id: str) -> str:
    """The epic's plan and state, as markdown."""
    epic = store.show(epic_id)
    children = [t for t in store.list(parent=epic_id) if t.type != GATE]
    gated = {
        target
        for g in store.gate_list()
        for target in (g.depends_on or ())
    }
    gate_reason = {
        target: (g.description or g.title)
        for g in store.gate_list()
        for target in (g.depends_on or ())
    }

    done = [t for t in children if t.status == CLOSED]
    lines = [BANNER, ""]
    title = _gloss(epic.title, 12) if epic else "(epic not found in the tracker)"
    lines += [f"# {epic_id} — {title}", ""]
    if epic:
        lines.append(f"**status** {epic.status} · **children** {len(children)} · "
                     f"**closed** {len(done)}/{len(children)}")
        lines.append("")

    if not children:
        lines += ["No child tasks. The epic has not been planned yet.", ""]
        return "\n".join(lines)

    v = store.validate(epic_id)
    if v.waves:
        lines += ["## Waves", "",
                  "Dependency parallelism only — **this ignores file contention**, and an",
                  "epic has been rated 11-wide whose file graph supported about two.", ""]
        by_id = {t.id: t for t in children}
        for w in v.waves:
            # A GATED TASK IS NOT DISPATCHABLE, whatever the dependency graph says. The
            # levelling knows about edges and nothing else, so without this marker the
            # wave list and the gated section below contradict each other — and the wave
            # list is the one a reader acts on.
            names = ", ".join(
                ("🔒 " if tid in gated else "")
                + (f"`{tid}` ({_gloss(by_id[tid].title, 5)})" if tid in by_id else f"`{tid}`")
                for tid in w.task_ids
            )
            live = len([t for t in w.task_ids if t not in gated])
            width = f"{live} of {len(w.task_ids)}" if live != len(w.task_ids) else str(live)
            lines.append(f"- **wave {w.index + 1}** ({width} dispatchable) — {names}")
        lines.append("")
    if v.cycles:
        lines += ["> **CYCLE** — these depend on each other and no wave can contain them: "
                  + ", ".join(f"`{x}`" for c in v.cycles for x in c), ""]
    if v.orphans:
        lines += ["> **DANGLING EDGE** — depended on but absent from this epic: "
                  + ", ".join(f"`{x}`" for x in v.orphans), ""]

    lines += ["## Tasks", "",
              "| id | status | task | depends on | assignee |",
              "|---|---|---|---|---|"]
    for t in sorted(children, key=lambda x: (x.status != "in_progress", x.id)):
        mark = "✓" if t.status == CLOSED else ("⏳" if t.status == "in_progress" else "")
        if t.id in gated and t.status in OPEN_STATUSES:
            mark = "🔒"
        deps = ", ".join(f"`{d}`" for d in t.depends_on) or "—"
        lines.append(
            f"| `{t.id}` | {mark} {t.status} | {_gloss(t.title, 9)} | {deps} | "
            f"{t.assignee or '—'} |"
        )
    lines.append("")

    blocked = [t for t in children if t.id in gated and t.status in OPEN_STATUSES]
    if blocked:
        lines += ["## Gated — these need a human, not a worker", ""]
        for t in blocked:
            lines.append(f"- `{t.id}` ({_gloss(t.title, 6)}) — {gate_reason.get(t.id, 'no reason recorded')}")
        lines.append("")
    return "\n".join(lines)


def write(store: TaskStore, epic_id: str, dest: Path) -> bool:
    """Write the view. Returns whether the content changed."""
    text = render_epic(store, epic_id)
    dest = Path(dest)
    if dest.is_file() and dest.read_text() == text:
        return False
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(text)
    return True


def check(store: TaskStore, epic_id: str, dest: Path) -> str | None:
    """None when the file matches what would be generated, else why it does not."""
    dest = Path(dest)
    if not dest.is_file():
        return f"{dest} does not exist — run `tk.sh render {epic_id} --write {dest}`"
    if dest.read_text() != render_epic(store, epic_id):
        return (
            f"{dest} disagrees with the tracker. It is GENERATED: regenerate it rather "
            f"than editing it, or the file becomes a second source of truth."
        )
    return None
