"""Resolve and run a stack's declared commands — one call, many commands.

THE FOURTH BATCHING PRIMITIVE. `scan.sh`, `peek.sh` and `brief.sh` batch *reads*,
and reads are toolchain-neutral: they are `git grep`, `git show` and `git diff`.
Nothing batched *runs*, so the wave gate composes `lint && typecheck && test` by
hand from config it cannot conveniently read, every wave, per stack — and
`swarm.md` §8 points at `check-project-config.sh` to print those commands, which
it does not do.

The cost model is the same one `evidence-gathering` argues from:

    tokens ~= 18,700 + 2,600 x tool_calls

so collapsing three toolchain calls into one is worth ~5,200 tokens per agent per
wave. That is the whole reason this exists as a primitive rather than as prose
telling an orchestrator to remember to combine them.

TWO PROPERTIES THAT MATTER MORE THAN THE SAVING, both inherited deliberately:

  * **Every input produces an output.** A key the stack does not declare is
    reported ABSENT, never silently dropped. A batch that quietly loses an input
    is worse than the calls it replaced, because the caller reasons from a partial
    answer believing it is whole. `test_batching.py` pins this for `scan`/`peek`;
    it is pinned here too.
  * **A timeout is its own outcome, never a pass.** The recorded 8.5-hour stall
    was a command that matched no permission rule and blocked on a prompt in
    another session. A probe that can hang without saying so would reproduce it.

This module is the shared resolver. `check_commands.py` sits on it for the
pre-flight probe, and `harness/verify/mutate.sh` uses it instead of the private
lookup it used to carry.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import time
from dataclasses import dataclass
from pathlib import Path

from .project import Project, Stack, load
from .resolve import CHECKOUT

#: Long enough for a scoped suite, short enough that a hung command is caught
#: within one agent's patience rather than an orchestrator's.
DEFAULT_TIMEOUT = 600

#: A verification probe does no work, so it gets a far tighter bound. A
#: collect-only against a large suite was measured at ~3.4s.
PROBE_TIMEOUT = 60

#: Set in the environment of every command this module runs, and refused if already
#: present. A probe derives its candidates from what the repository declares, and an
#: aggregate target like `make test` legitimately runs the whole suite — which runs
#: the harness's own tests, which probe again. Measured: the suite hung indefinitely
#: with no error, because each level was politely waiting on the next.
#:
#: A depth counter would let one level of nesting through; there is no reason to want
#: one. A flat refusal breaks the cycle at the first re-entry and says why.
REENTRY_GUARD = "MAD_HARNESS_PROBING"


#: The per-worker environment a swarm worktree carries. `run_key` loads it, so a worker
#: never has to write `source .swarm-env && …` — a form that CANNOT BE PERMITTED.
#:
#: Measured: a compound command is denied even when every part of it is granted.
#: `source .swarm-env && uv run pytest` is refused with BOTH `Bash(source:*)` and
#: `Bash(uv:*)` in force, while a plain `uv run pytest` is allowed. That is the same
#: family as the recorded multi-hour stall — a command string that no prefix rule can
#: match — and `source && …` was the FIX for that one, carrying the same defect.
SWARM_ENV = ".swarm-env"


def _worker_env(cwd: Path) -> dict[str, str]:
    """Variables exported by `.swarm-env`, if the worktree has one.

    A five-line parser rather than a shell: the file is generated by `worker.py` and holds
    `export KEY=value` lines and comments. Running a shell to read it would reintroduce
    the very compound command this exists to avoid.
    """
    path = Path(cwd) / SWARM_ENV
    out: dict[str, str] = {}
    try:
        text = path.read_text()
    except OSError:
        return out
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export ") :]
        key, sep, value = line.partition("=")
        if sep and key:
            out[key.strip()] = value.strip().strip("'\"")
    return out


def probing() -> bool:
    """Whether this process is already inside a command probe."""
    return bool(os.environ.get(REENTRY_GUARD))


#: Outcome statuses. `absent` and `no_tool` are NOT failures of the command —
#: they are failures to have one, which a caller may treat differently.
OK = "ok"
FAILED = "failed"
ABSENT = "absent"
NO_TOOL = "no-tool"
TIMEOUT = "timeout"
#: Refused rather than run — see REENTRY_GUARD. Not a pass and not a failure.
SKIPPED = "skipped"


class ProjectCommandError(RuntimeError):
    """The request names something this project does not have."""


@dataclass(frozen=True)
class Outcome:
    """One command's result. Every requested key produces exactly one of these."""

    stack: str
    key: str
    status: str
    command: str = ""
    cwd: str = "."
    returncode: int | None = None
    detail: str = ""
    duration_s: float = 0.0

    @property
    def ok(self) -> bool:
        return self.status == OK

    @property
    def ran(self) -> bool:
        """Whether the command was actually executed, however it turned out."""
        return self.status in (OK, FAILED, TIMEOUT)

    def line(self) -> str:
        mark = {
            OK: "ok  ",
            FAILED: "FAIL",
            ABSENT: "--  ",
            NO_TOOL: "TOOL",
            TIMEOUT: "HUNG",
        }[self.status]
        tail = f"  {self.detail}" if self.detail else ""
        secs = f" {self.duration_s:.1f}s" if self.ran else ""
        return f"  [{mark}] {self.stack}:{self.key:<14}{secs:>7}  {self.command}{tail}"


def stacks_for(lane: str | None, project: Project | None = None) -> list[Stack]:
    """The stacks in play for `lane`.

    Mirrors `context.active_modules`, including its central judgement: an unmapped
    lane returns EVERYTHING rather than nothing. Running one command too many is
    recoverable; silently running none is a green result that measured nothing.
    """
    p = project or load()
    wanted = (p.raw.get("lanes") or {}).get(lane) if lane else None
    if not wanted:
        return list(p.stacks)
    names = set(wanted.get("stacks") or ())
    picked = [s for s in p.stacks if s.name in names]
    return picked or list(p.stacks)


def resolve(stack: Stack, key: str, path: str | None = None) -> str | None:
    """The command string for `key`, or None when the stack does not declare it.

    `{path}` is substituted where the command declares it. A command with no
    placeholder is returned unchanged even when a path was supplied — that is the
    module's statement that this command is not scopeable, and silently appending
    the path would invent a shape it never claimed to accept.
    """
    cmd = (stack.commands or {}).get(key)
    if not cmd:
        return None
    if "{path}" in cmd:
        return cmd.replace("{path}", path or "")
    return cmd


def tool_of(command: str) -> str:
    """The executable a command starts with — `uv run pytest` -> `uv`.

    Used for the free existence probe. Deliberately naive: a command that does not
    begin with its executable is the banned inline-env form, which this harness
    already refuses everywhere else.
    """
    return command.strip().split()[0] if command.strip() else ""


def run_key(
    stack: Stack,
    key: str,
    *,
    path: str | None = None,
    timeout: int = DEFAULT_TIMEOUT,
    check_tool: bool = True,
    runner=None,
) -> Outcome:
    """Run one declared command and report what happened. Never raises.

    :param runner: injected for tests; defaults to :func:`subprocess.run`.
    """
    command = resolve(stack, key, path)
    if not command:
        return Outcome(
            stack=stack.name,
            key=key,
            status=ABSENT,
            detail=f"stack {stack.name!r} declares no {key!r} command",
        )

    # THE CHECKOUT, NOT THE PROJECT. A worker's tests must run in its worktree; run in
    # REPO they tested the primary and stayed green with the worker's code broken.
    cwd = CHECKOUT / stack.commands_cwd
    tool = tool_of(command)
    if check_tool and tool and not shutil.which(tool):
        # The free rung. A missing executable
        # is a different diagnosis from a failing command, and reporting them the
        # same way sends the reader to debug the wrong thing.
        return Outcome(
            stack=stack.name,
            key=key,
            status=NO_TOOL,
            command=command,
            cwd=stack.commands_cwd,
            detail=f"{tool!r} is not on PATH",
        )
    if not cwd.is_dir():
        return Outcome(
            stack=stack.name,
            key=key,
            status=FAILED,
            command=command,
            cwd=stack.commands_cwd,
            detail=f"cwd {stack.commands_cwd!r} does not exist under {CHECKOUT}",
        )

    if probing():
        # Re-entry. A candidate ran us; running it again would recurse until the
        # outer timeout, or forever. Report it rather than pretending it passed.
        return Outcome(
            stack=stack.name,
            key=key,
            status=SKIPPED,
            command=command,
            cwd=stack.commands_cwd,
            detail=(
                f"refused: already inside a probe ({REENTRY_GUARD} is set). A candidate "
                f"command re-entered the harness; nothing was run."
            ),
        )

    run = runner or subprocess.run
    started = time.monotonic()
    try:
        proc = run(
            command,
            shell=True,
            cwd=str(cwd),
            capture_output=True,
            text=True,
            timeout=timeout,
            # The worker's own isolated resources — its database above all. Without
            # them a worker's suite falls through to the shared default and parallel
            # workers corrupt each other's fixtures WHILE STILL GOING GREEN.
            # `.swarm-env` sits at the WORKTREE ROOT, not in the stack's command
            # directory — for a project whose toolchain lives in `backend/` it was never
            # found, and the worker's suite ran on the shared default database.
            env={**os.environ, **_worker_env(CHECKOUT), REENTRY_GUARD: "1"},
        )
    except subprocess.TimeoutExpired:
        return Outcome(
            stack=stack.name,
            key=key,
            status=TIMEOUT,
            command=command,
            cwd=stack.commands_cwd,
            detail=(
                f"no output within {timeout}s. A command that hangs is usually one "
                f"blocking on a permission prompt in another session — check its form."
            ),
            duration_s=time.monotonic() - started,
        )
    except OSError as exc:
        return Outcome(
            stack=stack.name,
            key=key,
            status=FAILED,
            command=command,
            cwd=stack.commands_cwd,
            detail=str(exc)[:200],
            duration_s=time.monotonic() - started,
        )

    elapsed = time.monotonic() - started
    rc = proc.returncode
    log = _keep_log(stack.name, key, proc.stdout or "", proc.stderr or "")
    detail = ""
    if rc != 0:
        detail = _digest(proc.stdout or "", proc.stderr or "", rc, log)
    elif log is not None:
        detail = f"log: {_rel(log)}"
    return Outcome(
        stack=stack.name,
        key=key,
        status=OK if rc == 0 else FAILED,
        command=command,
        cwd=stack.commands_cwd,
        returncode=rc,
        detail=detail,
        duration_s=elapsed,
    )


#: Where a stack command's whole output goes. Under the CHECKOUT — a worker's own
#: worktree — beside the telemetry, and ignored by git like the rest of `.harness/run/`.
LOG_DIR = ".harness/run/out"
#: Lines a failing run is summarised by. Runner-neutral on purpose — the stack declares
#: the command, not its output format — so two tiers: the line that NAMES a failure
#: (a test runner's per-test verdict, a compiler's diagnostic) and the lines that
#: explain one (an assertion, a stack frame), which only fill what the names leave.
FAILURE_NAME = re.compile(r"^(FAILED|ERROR|FAIL\b|✗|×|●)")
FAILURE_DETAIL = re.compile(r"(?:^|\s)(?:error|Error)(?: TS\d+)?:\s|^E   |^\s+at ")
DIGEST_FAILURES = 12
DIGEST_TAIL = 4


def _keep_log(stack: str, key: str, out: str, err: str) -> Path | None:
    """The whole output, kept where the worker can window it. A result is paid on every
    later turn, so the report prints a digest and this path — `peek.sh <path>:START-END`
    reads a section — instead of the output. Before this the output was captured and
    discarded, and a worker that saw `[FAIL]` re-ran the suite raw to learn why, paying
    the whole output into its context. Never fails a run: an unwritable directory means
    no path, and the digest still says what failed."""
    try:
        d = CHECKOUT / LOG_DIR
        d.mkdir(parents=True, exist_ok=True)
        path = d / f"{stack}-{key}.log"
        parts = [out] if out.strip() else []
        if err.strip():
            parts.append("[stderr]\n" + err)
        path.write_text("\n".join(parts))
        return path
    except OSError:
        return None


def _rel(path: Path) -> str:
    try:
        return str(path.relative_to(CHECKOUT))
    except ValueError:
        return str(path)


def _digest(out: str, err: str, rc: int, log: Path | None) -> str:
    """What went wrong, in a dozen lines: the per-failure lines the runner printed, the
    last few lines (a runner's summary sits there), and where the rest is."""
    text = (out + "\n" + err).strip()
    if not text:
        return f"exit {rc}" + (f"  full: {_rel(log)}" if log else "")
    lines = text.splitlines()
    names = [ln[:160] for ln in lines if FAILURE_NAME.match(ln)]
    details = [ln[:160] for ln in lines if not FAILURE_NAME.match(ln) and FAILURE_DETAIL.search(ln)]
    shown = names[:DIGEST_FAILURES] + details[: max(0, DIGEST_FAILURES - len(names))]
    tail = [ln[:160] for ln in lines[-DIGEST_TAIL:] if ln.strip() and ln[:160] not in shown]
    parts = [f"exit {rc}"]
    if len(names) + len(details) > len(shown):
        parts.append(f"{len(names)} failures named, {len(details)} detail lines; showing {len(shown)}:")
    parts += shown + tail
    if log:
        parts.append(f"full: {_rel(log)} ({len(lines)} lines)")
    return "\n         ".join(parts)


def run_keys(
    keys: list[str],
    *,
    lane: str | None = None,
    stack_name: str | None = None,
    path: str | None = None,
    timeout: int = DEFAULT_TIMEOUT,
    project: Project | None = None,
    runner=None,
) -> list[Outcome]:
    """Run several keys across the stacks in play. One call, every key answered."""
    p = project or load()
    stacks = stacks_for(lane, p)
    if stack_name:
        stacks = [s for s in stacks if s.name == stack_name]
        if not stacks:
            declared = ", ".join(s.name for s in p.stacks) or "<none>"
            raise ProjectCommandError(
                f"no stack named {stack_name!r} in this project; declared: {declared}"
            )
    return [
        run_key(s, k, path=path, timeout=timeout, runner=runner)
        for s in stacks
        for k in keys
    ]


def report(outcomes: list[Outcome]) -> str:
    lines = [o.line() for o in outcomes]
    ran = [o for o in outcomes if o.ran]
    bad = [o for o in outcomes if o.status in (FAILED, TIMEOUT)]
    absent = [o for o in outcomes if o.status == ABSENT]
    notool = [o for o in outcomes if o.status == NO_TOOL]
    summary = (
        f"\n{len(ran)} ran, {len(bad)} failed, {len(absent)} not declared, "
        f"{len(notool)} with no toolchain on PATH."
    )
    if absent:
        summary += (
            "\nA key reported `--` is one the stack does not declare. That is an "
            "answer, not a skipped step: declare it or stop asking for it."
        )
    return "\n".join(lines) + summary


def main(argv: list[str] | None = None) -> int:
    import argparse
    import sys

    ap = argparse.ArgumentParser(
        prog="run.sh",
        description="Run a stack's declared commands — many in one call.",
        epilog=(
            "Every key you name produces a line, including keys the stack does not "
            "declare. Exit is non-zero if any command ran and failed."
        ),
    )
    ap.add_argument("keys", nargs="+", help="command keys, e.g. lint typecheck test")
    ap.add_argument("--lane", default=None, help="restrict to this lane's stacks")
    ap.add_argument("--stack", default=None, help="restrict to one stack by name")
    ap.add_argument("--scoped", default=None, help="path for a {path} placeholder")
    ap.add_argument("--timeout", type=int, default=DEFAULT_TIMEOUT)
    ap.add_argument(
        "--print",
        dest="print_only",
        action="store_true",
        help="resolve without running: print the command and its cwd, two lines, "
        "for a shell caller that drives the command itself (mutate.sh)",
    )
    args = ap.parse_args(argv)

    if args.print_only:
        p = load()
        for s in stacks_for(args.lane, p):
            if args.stack and s.name != args.stack:
                continue
            cmd = resolve(s, args.keys[0], args.scoped)
            if cmd:
                # cwd is root-relative: a stack in services/api runs there, not at
                # the repository root. Resolving it here is why the caller must not
                # read `commands.cwd` itself.
                print(cmd)
                print(s.commands_cwd)
                return 0
        return 3

    try:
        outcomes = run_keys(
            args.keys,
            lane=args.lane,
            stack_name=args.stack,
            path=args.scoped,
            timeout=args.timeout,
        )
    except ProjectCommandError as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 2

    print(report(outcomes))
    return 1 if any(o.status in (FAILED, TIMEOUT) for o in outcomes) else 0


if __name__ == "__main__":
    raise SystemExit(main())
