"""Prepare one swarm worker's worktree, from the stack modules that describe it.

THE HIGHEST-CONSEQUENCE CODE IN THE HARNESS. What this writes into `.swarm-env`
decides whether parallel workers get their own database or silently share one —
and sharing does not fail loudly. The suite still goes green; the corruption
surfaces days later as an unrelated flake in somebody else's wave. That invariant
has broken three times. The first two fixes were documentation, and both failed,
because the script every worker actually runs still contradicted the prose.

So the values are no longer typed here. They are DERIVED from the stack modules
that own them: a Python toolchain declares a per-worker database name because that
is a fact about running its test runner, and a Node one declares a per-worker build
directory because parallel builds must not share output.
There is one source of truth and the shell script is a thin caller.

Bootstrap strategy also comes from the stack, and the two differ for a reason:

  install   when the package manager hardlinks or caches, so a per-worktree copy
            costs seconds.
  symlink   when the directory is large AND concurrent readers are safe, so linking
            to the primary checkout beats installing.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from .project import Project, load


class WorkerError(RuntimeError):
    """The worktree could not be prepared, and a worker must not start without one."""


def main_checkout(start: Path) -> Path:
    """The primary checkout, resolved from anywhere inside the repo or a worktree."""
    top = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        cwd=str(start),
        capture_output=True,
        text=True,
    )
    if top.returncode != 0:
        raise WorkerError(f"{start} is not inside a git repository")
    listing = subprocess.run(
        ["git", "worktree", "list", "--porcelain"],
        cwd=top.stdout.strip(),
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    for line in listing.splitlines():
        if line.startswith("worktree "):
            return Path(line.split(" ", 1)[1])
    raise WorkerError("git worktree list returned no primary checkout")


def env_block(
    worker: int, lane: str, main: Path, project: Project | None = None
) -> str:
    """The exact contents of `.swarm-env`, as a pure function of the config.

    Pure on purpose: it can be asserted in a test without running the script,
    which would create a git worktree — persistent repo state that a failing test
    would then leave behind, a worse outcome than the bug being guarded.
    """
    p = project or load()
    stack_env = p.worker_env(worker)
    swarm = p.raw.get("swarm") or {}

    lines = [
        "# Generated by harness/models/worker.py from harness.yaml and",
        "# harness/stacks/. Do not hand-edit — regenerate by re-running the init.",
        # The tracker-neutral identity every backend's claim uses. BEADS_ACTOR stays
        # beside it while tasks is in play — bd reads that name and nothing else.
        f"export TRACKER_ACTOR=swarm-w{worker}",
        f"export BEADS_ACTOR=swarm-w{worker}",
        f"export BEADS_DB={main}/.beads/embeddeddolt",
    ]

    # Each stack may explain WHY a variable matters; the harness does not know.
    notes = {}
    for st in p.stacks:
        for var, why in (st.bootstrap.get("env_notes") or {}).items():
            notes[var] = why
    for var in sorted(stack_env):
        if var in notes:
            lines += [f"# {line}" for line in str(notes[var]).strip().splitlines()]
        lines.append(f"export {var}={stack_env[var]}")

    for alias, source in (swarm.get("aliases") or {}).items():
        if source in stack_env:
            lines.append(
                f"export {alias}={stack_env[source]}  # legacy alias for {source}"
            )

    if swarm.get("merge_slot"):
        lines.append(f"export SWARM_SLOT={swarm['merge_slot']}")
    lines.append(f"export SWARM_LANE={lane}")
    # Only where the project declares a design handover. This was exported into every
    # worker in every project — including ones with no handover, no Node and no
    # browser — and it was the one hardcoded non-tracker variable left in a file whose
    # whole docstring is about values being derived rather than typed.
    if p.raw.get("fidelity"):
        lines.append(f"export FIDELITY_NAME_PREFIX=w{worker}-")
    return "\n".join(lines) + "\n"


def bootstrap(worktree: Path, main: Path, project: Project | None = None) -> list[str]:
    """Restore what a fresh worktree lacks, per stack. Returns log lines."""
    p = project or load()
    log: list[str] = []
    for s in p.stacks:
        deps = s.deps_path
        target = worktree / deps
        if target.exists():
            log.append(f"==> {deps} present, skipping ({s.name})")
            continue
        strategy = (s.bootstrap or {}).get("strategy", "install")
        if strategy == "none":
            # Nothing to restore: the manager resolves on demand from a tracked file.
            # `probe-worktree.sh`'s first run found the harness's own stack declaring
            # this in a comment while its strategy said `symlink` to a directory that
            # never existed — every worker worktree on it would have refused to init.
            log.append(f"==> nothing to restore ({s.name})")
            continue
        if strategy == "symlink":
            source = main / deps
            if not source.exists():
                raise WorkerError(
                    f"{s.name}: cannot symlink {deps} — {source} does not "
                    f"exist in the primary checkout. Install it there first."
                )
            target.parent.mkdir(parents=True, exist_ok=True)
            target.symlink_to(source)
            log.append(f"==> symlinked {deps} -> primary checkout ({s.name})")
        elif strategy == "install":
            cmd = (s.bootstrap or {}).get("command")
            if not cmd:
                raise WorkerError(
                    f"{s.name}: bootstrap strategy is 'install' but no command"
                )
            rel = s.bootstrap_cwd
            cwd = worktree / rel
            if not cwd.is_dir():
                raise WorkerError(
                    f"{s.name}: bootstrap cwd {rel!r} does not exist under {worktree}. "
                    f"Either this is not the worktree root, or the stack's `root` "
                    f"({s.root!r}) is wrong for this repository's layout."
                )
            log.append(f"==> {cmd}  (cwd={rel}, {s.name})")
            proc = subprocess.run(
                cmd, shell=True, cwd=str(cwd), capture_output=True, text=True
            )
            if proc.returncode != 0:
                raise WorkerError(
                    f"{s.name}: `{cmd}` failed: {proc.stderr.strip()[:300]}"
                )
        else:
            raise WorkerError(f"{s.name}: unknown bootstrap strategy {strategy!r}")
    return log


def init(worker: int, lane: str, worktree: Path | None = None) -> int:
    wt = (worktree or Path.cwd()).resolve()
    main = main_checkout(wt).resolve()

    print(f"==> worker w{worker} (lane={lane})")
    print(f"    main checkout: {main}")
    print(f"    worktree:      {wt}")

    # Refusing beats proceeding: a writer in the primary checkout edits the tree
    # every sibling is reading, and nothing downstream would catch it.
    if wt == main:
        print(
            "!!  refusing to run in the primary checkout — run this from inside a worktree",
            file=sys.stderr,
        )
        return 1

    for line in bootstrap(wt, main):
        print(line)

    envfile = wt / ".swarm-env"
    envfile.write_text(env_block(worker, lane, main))
    print(f"==> wrote {envfile}")
    for line in envfile.read_text().splitlines():
        if line.startswith("export "):
            print(f"    {line[len('export ') :]}")

    # The commands come from the stacks, not from here. This is the last thing a
    # worker reads before its first test run, and printing one project's runner at
    # every other project was the review's sharpest instance of hardcoded layout.
    print()
    for s in load().stacks:
        key = "test_first_run" if s.commands.get("test_first_run") else "test_scoped"
        if not s.commands.get(key):
            continue
        print(f"==> first run for {s.name}:")
        # THROUGH THE RUNNER, which loads .swarm-env itself. Two forms are ruled out and
        # both were once printed here. An inline env assignment (`VAR=x uv run ...`)
        # matches no prefix permission rule and blocks on a prompt that surfaces in the
        # ORCHESTRATOR's session — a recorded multi-hour stall, three times over. And
        # `source .swarm-env && ...`, which was the fix for that, carries the same defect:
        # a compound command is denied even when every part of it is granted. Sourcing
        # could not have worked regardless, since every Bash call is a fresh shell.
        print(f"    harness/verify/run.sh --lane <lane> {key}   # loads .swarm-env for you")
    return 0


def default_lane() -> str:
    """The first lane this project declares.

    `backend` was a literal here, which is one project's vocabulary: a repo whose lanes
    are `api` and `web` would silently get a lane it never declared.
    """
    lanes = load().raw.get("lanes") or {}
    return next(iter(lanes), "default")


def main(argv: list[str] | None = None) -> int:
    import argparse

    ap = argparse.ArgumentParser(prog="swarm-worktree-init.sh", add_help=True)
    ap.add_argument("worker", type=int)
    ap.add_argument(
        "lane",
        nargs="?",
        default=None,
        help="defaults to the first lane declared in harness.yaml",
    )
    ap.add_argument(
        "--worktree",
        type=Path,
        default=None,
        help="the worktree root; the shell wrapper passes its own cwd, "
        "which would otherwise be lost when it cd's to the module root",
    )
    try:
        args = ap.parse_args(argv if argv is not None else sys.argv[1:])
    except SystemExit:
        return 2
    try:
        return init(args.worker, args.lane or default_lane(), args.worktree)
    except WorkerError as exc:
        print(f"!!  {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
